---
title: "LIM"
author: "ChuehChenTung"
date: '2023-04-26'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(fig.width=8, fig.height=6) 
```

<font size="4"> 
**Caption:**
The conceptual model plotted with LIM results of GC1 and GS1 processed with the MCMC algorithm.

</font>

```{r}
rm(list=ls())
library(patchwork)
#-- Load the LIM (and limSolve) package 
library(LIM)
library(splus2R)
#MODEL SETUP####
#-- Define directory that contains the input file
DataDir <- "C:/Users/user/Downloads/GPSC_data/for_pub/RMD/"
#GC1####
load(file="GC1_10000_50.Rdata")
GC1_LIM<-LIM
GC1_xs<-xs
#GS1####
load(file="GS1_10000_50.Rdata")
GS1_LIM<-LIM
GS1_xs<-xs

rescale <- function(x, from, to) {
  maxx <- max(x)
  minx <- min(x)
  out <- (to - from) * (x - minx)
  out <- out / (maxx - minx)
  out + from
}

GC1<-data.frame(flow=GC1_LIM$Unknowns,
                mean=round(colMeans(GC1_xs$X),3),
                station="GC1")
GS1<-data.frame(flow=GS1_LIM$Unknowns,
                mean=round(colMeans(GS1_xs$X),3),
                station="GS1")
df<-rbind(GC1,GS1)
df$arrow=round(rescale(df$mean,1,15),2)
df
library(DiagrammeR)
library(DiagrammeRsvg)
library(magrittr)
library(rsvg)

#GC1####
GC1_graph<-grViz("
digraph{
   graph[rankdir=TB]
  
  {rank=1
    node [shape=box style=filled fillcolor=lightsteelblue]
    POC_W [label=POC]
    EXP_S [label=Export]
    DIC_W [label=DIC]
    EXP_B [label=Predation]
  }
  
  {
    rank=2
    node [style=filled fillcolor=Coral]
    DET [label=Sediment]
    BAC [label=Bacteria]
    MEI [label=Meiofauna]
    MAC [label=Macrofauna]
    }  
  {
    rank=3
    node [shape=box style=filled fillcolor=lightsteelblue]
    BUR   [label=Burial]
  }  
  {
  # POM input
  POC_W -> DET [color = tomato fontcolor=steelblue3 label=1265.388 penwidth=15.00]
  # POM burial
  DET -> BUR [color = tomato fontcolor=steelblue3 label=181.312 penwidth=3.01]
  # POM export
  DET -> EXP_S [color = tomato fontcolor=steelblue3 label=1068.555 penwidth=12.82]
  
  # Deposit feeding
  DET -> BAC   [color = black  fontcolor=steelblue3 label=28.818 penwidth=1.32]
  DET -> MEI   [color = black fontcolor=steelblue3 label=0.153  penwidth=1.00]
  DET -> MAC   [color = black  fontcolor=steelblue3 label=0.006  penwidth=1.00]
  
  #Faeces
  BAC -> DET   [color = black fontcolor=steelblue3 label=13.312 penwidth=1.15]
  MEI -> DET   [color = black fontcolor=steelblue3 label=0.138 penwidth=1.00]
  MAC -> DET   [color = black  fontcolor=steelblue3 label=0.007 penwidth=1.00]
  
  # Interaction
  # BAC
  BAC -> MEI   [color = black fontcolor=steelblue3 label=0.150 penwidth=1.00]
  BAC -> MAC   [color = black fontcolor=steelblue3 label=0.006 penwidth=1.00]

  # MEI
  MEI -> MAC   [color = black fontcolor=steelblue3 label=0.006 penwidth=1.00]
  
  # Predation
  MEI -> EXP_B   [color = gray fontcolor=steelblue3 label=0.053 penwidth=1.00]
  MAC -> EXP_B   [color = gray fontcolor=steelblue3 label=0.008 penwidth=1.00]
 
  # Respiration
  BAC -> DIC_W [color = gray fontcolor=steelblue3 label=15.350 penwidth=1.17]
  MEI -> DIC_W [color = gray fontcolor=steelblue3 label=0.105 penwidth=1.00]
  MAC -> DIC_W [color = gray fontcolor=steelblue3 label=0.004 penwidth=1.00]
}    
}
")
GC1_graph%>%
  export_svg %>% charToRaw %>% rsvg_png("GC1_graph.png")

#GS1####
GS1_graph<-grViz("
digraph{
   graph[rankdir=TB]
  
  {rank=1
    node [shape=box style=filled fillcolor=lightsteelblue]
    POC_W [label=POC]
    EXP_S [label=Export]
    DIC_W [label=DIC]
    EXP_B [label=Predation]
  }
  
  {
    rank=2
    node [style=filled fillcolor=Coral]
    DET [label=Sediment]
    BAC [label=Bacteria]
    MEI [label=Meiofauna]
    MAC [label=Macrofauna]
    }  
  {
    rank=3
    node [shape=box style=filled fillcolor=lightsteelblue]
    BUR   [label=Burial]
  }  
  {
  # POM input
  POC_W -> DET [color = tomato fontcolor=steelblue3 label=105.463 penwidth=2.17]
  # POM burial
  DET -> BUR [color = tomato fontcolor=steelblue3 label=77.964 penwidth=1.86]
  # POM export
  DET -> EXP_S [color = tomato fontcolor=steelblue3 label=12.113 penwidth=1.13]
  
  # Deposit feeding
  DET -> BAC   [color = black  fontcolor=steelblue3 label=22.340 penwidth=1.25]
  DET -> MEI   [color = black fontcolor=steelblue3 label=5.157  penwidth=1.06]
  DET -> MAC   [color = black  fontcolor=steelblue3 label=0.340  penwidth=1.00]
  
  #Faeces
  BAC -> DET   [color = black fontcolor=steelblue3 label=8.654 penwidth=1.10]
  MEI -> DET   [color = black fontcolor=steelblue3 label=3.527 penwidth=1.04]
  MAC -> DET   [color = black  fontcolor=steelblue3 label=0.270 penwidth=1.00]
  
  # Interaction
  # BAC
  BAC -> MEI   [color = black fontcolor=steelblue3 label=2.153 penwidth=1.02]
  BAC -> MAC   [color = black fontcolor=steelblue3 label=0.221 penwidth=1.00]

  # MEI
  MEI -> MAC   [color = black fontcolor=steelblue3 label=0.192 penwidth=1.00]
  
  # Predation
  MEI -> EXP_B   [color = gray fontcolor=steelblue3 label=1.143 penwidth=1.01]
  MAC -> EXP_B   [color = gray fontcolor=steelblue3 label=0.311 penwidth=1.00]
 
  # Respiration
  BAC -> DIC_W [color = gray fontcolor=steelblue3 label=11.312  penwidth=1.13]
  MEI -> DIC_W [color = gray fontcolor=steelblue3 label=2.448  penwidth=1.03]
  MAC -> DIC_W [color = gray fontcolor=steelblue3 label=0.172 penwidth=1.00]
}    
}
")
GS1_graph%>%
  export_svg %>% charToRaw %>% rsvg_png("GS1_graph.png")
library(png)
library(grid)
library(gridExtra)
library(ggplotify)
library(cowplot)
library(ggplot2)
GC <- readPNG('GC1_graph.png')
GS <- readPNG('GS1_graph.png')
g<-grid.arrange(rasterGrob(GC),rasterGrob(GS),ncol=2)
p<-as.ggplot(g)+draw_plot_label(label = c("GC1","GS1"),x=c(0.05,0.55),y=c(0.93,0.93))
p
ggsave('LIM.png',p,width=12,height=5)

```