---
title: "Map"
author: "ChuehChenTung"
date: '2023-03-24'
output: html_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(fig.width=15, fig.height=10) 
```

<font size="4"> 
**Caption:**
Map of sampling stations visited From 2014 to 2020.
(A) The sampling area off the continental margin of SW Taiwan. (B) Sampling sites on the upper Gaoping Submarine Canyon (GC) and Gaoping Slope (GS),abbreviated as GC1 and GS1, respectively.

</font>

```{r}
rm(list=ls())
library(marmap)
library(ggplot2)
library(dplyr)
library(viridis)
library(readxl)
library(ggrepel)
library(ggsn)
library(ggOceanMaps)
library(patchwork)
library(ggspatial)
library(cowplot)

dt <- data.frame(lon = c(120, 120, 121, 121), lat = c(22, 23, 23, 22))


#geom_point(aes(x = 120.3,y = 22.5),color="red",size=2)

tw<-basemap(limits = c(110,135, 10, 40), bathymetry = F)+
  geom_polygon(data=dt,aes(x = lon,y = lat),color="red",fill=NA,size=0.4)+
  labs(title ="B")+
  xlab(NULL)+
  ylab(NULL)+
  theme_bw()+
  theme(axis.text = element_text(size = 9))

long_GC1 <- 120.4105
long_GS1 <- 120.3941
lat_GC1 <- 22.41653
lat_GS1 <- 22.24033
GPSC<-read.table('119_121_21_23.xyz',
                 col.names = c("long", "lat", "depth")) %>%
  data.frame %>% 
  filter(long > 120.25 & long < 120.7) %>% 
  filter(lat<22.7& lat > 22.1)

#plot

site<- ggplot()+
  xlab("Longitude")+ylab("Latitude")+
  geom_tile(data = GPSC[GPSC$depth >= 0,], 
            aes(x = long, y = lat), fill = "grey") +
  geom_raster(data = GPSC[GPSC$depth < 0 & GPSC$depth > -1000 ,],
              aes(x =long, y = lat, fill = depth)) +
  scale_fill_viridis(option = "G",limits = c(-1000, 0),
                     breaks = seq(0,-1000, -100),
                     labels = abs) +
  geom_contour(data =GPSC, aes(x=long, y=lat, z=depth),
               breaks=0,size=0.8,colour="black")+
  geom_contour(data =GPSC, aes(x=long, y=lat, z=depth),
               breaks=-100,size=0.3,colour="lightgrey")+
  geom_contour(data =GPSC, aes(x=long, y=lat, z=depth),
               breaks=-300,size=0.3,colour="lightgrey")+
  geom_contour(data =GPSC, aes(x=long, y=lat, z=depth),
               breaks=-500,size=0.3,colour="lightgrey")+
  geom_contour(data =GPSC, aes(x=long, y=lat, z=depth),
               breaks=-700,size=0.3,colour="lightgrey")+
  geom_point(aes(x = long_GC1, y = lat_GC1),color="black")+
  geom_text_repel(aes(x = long_GC1, y = lat_GC1, label = "GC1"), 
                  fontface = "bold", size=8,
                  nudge_x = c(-0.1), nudge_y = c(0.05)) +
  geom_point(aes(x = long_GS1, y = lat_GS1),color="black")+
  geom_text_repel(aes(x = long_GS1, y = lat_GS1, label = "GS1"), 
                  fontface = "bold", size=8,
                  nudge_x = c(0.1), nudge_y = c(0.05)) +
  coord_fixed(expand = FALSE) +
  labs(fill = "Depth (m)")+
  scale_x_continuous(breaks = seq(120.3, 120.6, 0.1), 
                     labels=c("120.3°E","120.4°E","120.5°E","120.6°E"))+
  scale_y_continuous(breaks = seq(22.2, 22.6, 0.1),
                     labels=c("22.2°N","22.3°N","22.4°N","22.5°N","22.6°N"))+
  scalebar(x.min=120.25, x.max=120.7, y.min=22.1, y.max= 22.7,
           model = "WGS84",  dist_unit = "km", transform = TRUE,
           location = "topright", anchor = c(x = 120.67, y = 22.13),
           height = 0.015, dist = 5, st.size = 3, border.size = 0.1) +
  labs(title ="A")+
  theme_bw()+theme(axis.text = element_text(size = 15),
                   axis.title.x = element_text(size = 18),
                   axis.title.y = element_text(size = 18),)

map<-ggdraw() +
  draw_plot(site,) +
  draw_plot(tw, x = 0.53, y = 0.65, width = 0.35, height = 0.35)
ggsave("map.png",map,width = 9, height =9)
map
```
